"use client";import{motion}from"framer-motion";import{ArrowUpRight,BrainCircuit,Database,Workflow,Play}from"lucide-react";
const projects = [
  [
    "AI Lead Qualification & CRM Automation",
    "AI AUTOMATION",
    "Lead intake → AI qualification → CRM → personalized email → reply detection → follow-up.",
    "/projects/ai-lead-qualification"
  ]
];
export default function Home(){return <main className="min-h-screen overflow-hidden"><div className="fixed inset-0 -z-10 grid-bg"/><section className="mx-auto max-w-6xl px-5 pb-24 pt-36 lg:px-8 lg:pt-44"><div className="grid items-center gap-14 lg:grid-cols-[1.2fr_.8fr]"><motion.div initial={{opacity:0,y:20}} animate={{opacity:1,y:0}}><div className="mb-7 flex gap-3 text-sm text-zinc-400"><span className="h-2 w-2 mt-2 rounded-full bg-[#00e5a8]"/>Available for AI engineering & automation projects</div><h1 className="text-5xl font-semibold leading-none tracking-tight sm:text-7xl lg:text-[82px]">I build <span className="accent">AI systems</span><br/>that do real work.</h1><p className="mt-8 max-w-2xl text-lg leading-8 text-zinc-400">AI Engineer focused on intelligent automations, agentic workflows, RAG systems and production-ready applications.</p><div className="mt-9 flex gap-3"><a href="/projects" className="rounded-full bg-white px-6 py-3.5 font-medium !text-black">Explore my work <ArrowUpRight className="inline ml-2" size={17}/></a><a href="/contact" className="rounded-full border border-white/10 px-6 py-3.5">Start a project</a></div></motion.div><div className="glass mx-auto aspect-[4/5] w-full max-w-sm rounded-[2rem]"><div className="flex h-full flex-col items-center justify-center text-center"><div className="h-48 w-48 overflow-hidden rounded-full border border-white/10">
  <img
    src="/profile.png"
    alt="Usama Jahanzaib"
    className="h-full w-full object-cover"
  />
</div><h2 className="mt-7 text-2xl font-semibold">Usama Jahanzaib</h2><p className="mt-2 text-sm text-zinc-500">AI Engineer · Automation · Agentic AI</p></div></div></div><div className="mt-20 grid gap-3 sm:grid-cols-3">{[["AI Automation","n8n · APIs · CRM"],["Agentic AI","LangGraph · LLMs"],["Production AI","FastAPI · Docker · DBs"]].map(x=><div className="glass rounded-2xl p-6" key={x[0]}><b>{x[0]}</b><p className="mt-2 text-sm text-zinc-500">{x[1]}</p></div>)}</div></section><section className="border-y border-white/[.06]"><div className="mx-auto max-w-6xl px-5 py-24 lg:px-8"><p className="text-xs tracking-[.18em] text-[#9d91ff]">WHAT I BUILD</p><h2 className="mt-4 text-4xl font-semibold sm:text-5xl">AI connected to real business processes.</h2><div className="mt-12 grid gap-4 md:grid-cols-3">{[["AI Automation",Workflow,"Business workflows connecting AI, APIs, CRMs and operations."],["AI Agents",BrainCircuit,"Agents that reason, use tools and execute multi-step tasks."],["RAG & Vision",Database,"Document intelligence, retrieval and visual understanding."]].map(([t,I,d])=><div className="glass rounded-2xl p-7" key={String(t)}><I/><h3 className="mt-7 text-xl">{String(t)}</h3><p className="mt-3 text-sm leading-6 text-zinc-500">{String(d)}</p></div>)}</div></div></section><section className="mx-auto max-w-6xl px-5 py-24 lg:px-8"><p className="text-xs tracking-[.18em] text-[#9d91ff]">SELECTED WORK</p><h2 className="mt-4 text-4xl font-semibold sm:text-5xl">Built, not just imagined.</h2><div className="mt-12 space-y-5">{projects.map((p,i)=><a href={p[3]} key={p[0]}><motion.article whileHover={{y:-3}} className="glass overflow-hidden rounded-3xl"><div className="grid lg:grid-cols-[.7fr_1.3fr]"><div className="flex min-h-[240px] flex-col justify-between bg-[radial-gradient(circle_at_70%_35%,rgba(124,92,255,.2),transparent_38%),#0b0e13] p-7"><span className="text-xs tracking-[.18em] text-[#9d91ff]">{p[1]}</span><span className="text-xs text-zinc-600">CASE STUDY 0{i+1}</span></div><div className="p-7 lg:p-10"><h3 className="text-2xl font-medium">{p[0]}</h3><p className="mt-4 text-sm leading-7 text-zinc-500">{p[2]}</p><span className="mt-8 inline-flex text-sm">View case study <ArrowUpRight className="ml-2" size={16}/></span></div></div></motion.article></a>)}</div></section><section className="mx-auto max-w-6xl px-5 pb-28 lg:px-8"><div className="glass rounded-3xl p-9 sm:p-14"><p className="text-xs tracking-[.18em] text-[#9d91ff]">LET&apos;S BUILD</p><h2 className="mt-4 text-4xl font-semibold sm:text-5xl">Have a process worth automating?</h2><a href="/contact" className="mt-7 inline-block rounded-full bg-white px-6 py-3.5 font-medium !text-black">Start a conversation</a></div></section></main>}